fix(Input): Add `wrapperContainerStyle` prop
cengage/react-magma pull request #1298
Opened 2024-05-24 15:28 UTC by silvalaura

Issue: #

## What I did

Add `wrapperContainerStyle` prop to allow more flexibility with Input widths

## Screenshots:

![image](https://github.com/cengage/react-magma/assets/91160746/37c0615b-7a80-457a-98df-d2326e95a827)

## Checklist 
- [ ] changeset has been added
- [ ] Pull request description is descriptive
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test

2024-05-24 15:32 UTC, silvalaura commented
TODO: 
- add unit test
- ensure label wraps
- isClearable???

2024-05-30 12:34 UTC, orion-cengage requested changes
I don't see an update to the documentation about this new prop. Maybe I misunderstood that it would be called out explicitly.

In the Storybook example, can we have isClearable turned off? I don't want to advertise the issue we have with the arrows.

I don't know how I missed this for so long, but the icon on the error message needs to be top aligned, not center.

![image](https://github.com/cengage/react-magma/assets/24397282/c3f7e3e4-3d7d-4db0-89e9-866d1f04d68e)

![image](https://github.com/cengage/react-magma/assets/24397282/70f091f5-8748-4c75-9a35-0c4a9fd1ad75)

2024-06-03 20:02 UTC, orion-cengage approved these changes

2024-06-06 14:27 UTC, merged

2024-06-11 17:50 UTC, ccedrone commented
✔️