fix(Select): Fix accessibility issue.
cengage/react-magma pull request #1434
Opened 2024-09-17 14:03 UTC by nikitaorliak-cengage

Issue: #1390

## What I did

Remove the `ClearIndicator` component outside from the `SelectTriggerButton`.

## Screenshots:

## Checklist 
- [x] changeset has been added
- [x] Pull request description is descriptive
- [ ] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test

2024-09-17 14:58 UTC, silvalaura commented
This looks good, and I verified the screenreader reads it on Safari.

However, because we are positioning it absolutely, it breaks in the examples with `labelPosition="left"` or when `isLabelVisuallyHidden` is true:
![image](https://github.com/user-attachments/assets/af2e9835-d4d2-49d6-ad52-1ee00fdefbb2)
![image](https://github.com/user-attachments/assets/73ab264c-281a-492a-a6c9-2f3578985e96)
![image](https://github.com/user-attachments/assets/5aa14e97-1803-449c-8d22-a215a63c7273)

2024-09-17 15:12 UTC, orion-cengage commented
We need to stop the clear button from overlapping the text and basically disappearing.

![image](https://github.com/user-attachments/assets/1d6e5193-e42c-4eb1-9097-f1cff5c104fb)

2024-09-17 15:17 UTC, orion-cengage commented
Not sure when this became an issue, but the regular Select is not supposed to grow vertically just because an item is long and wraps.

![image](https://github.com/user-attachments/assets/3b7294a9-73d4-400f-ae2e-28171b011341)

If anything, we should truncate it with ellipsis like this:

![image](https://github.com/user-attachments/assets/d6ee54d8-5938-494a-b38b-32228dff91b9)

2024-09-17 15:21 UTC, orion-cengage commented
The positioning of the clear button is off when it is in the error state or when showing helper text.

![image](https://github.com/user-attachments/assets/3858b306-1f1f-40cd-a82d-84c0c774ea1e)

![image](https://github.com/user-attachments/assets/0e8f3d11-ef3c-4c63-ae6b-407d5f180dd1)

2024-09-17 15:21 UTC, orion-cengage commented
The inverse version of the input isn't using the inverse version of the clear button so it is hard to see.

![image](https://github.com/user-attachments/assets/bad9df2f-dc04-4d87-a894-ddcd89c4616f)

2024-09-17 17:59 UTC, orion-cengage requested changes
I added a number of styling issues.

2024-09-18 20:14 UTC, orion-cengage requested changes
The latest update fixed the previous styling issues but has broken the focus style on the main container of the Select input. If we can fix this, then we might be good to go.

![image](https://github.com/user-attachments/assets/fb33209c-046a-4eab-ab25-169232c4bc75)

![image](https://github.com/user-attachments/assets/23071939-77b3-40b2-8576-67fe5985dd22)

![image](https://github.com/user-attachments/assets/d68bad1f-ff8a-4490-a6cd-534f5d57bee8)

2024-09-19 12:58 UTC, silvalaura commented
It's so close! 
- Focus is back ✅ 
- Text overflow is properly cut off ✅ 
- X is properly aligned for Combobox with left label ✅
- - X is properly aligned for Combobox with top label ✅ 
- X is properly aligned for Select with left label ✅ 
- X is properly aligned for Select with top label ❌ 
- Is inverse looks good ✅

2024-09-19 15:49 UTC, silvalaura commented
One more:
if Select `isMulti` is set to true, the isClearable button disappears. (it is visible for Combobox `isMulti`)
![image](https://github.com/user-attachments/assets/9e65b517-af0d-4246-aeaa-b7edc57b4d35)

All other use cases look good to me.

2024-09-20 15:37 UTC, silvalaura reviewed
**Select:**
- Focus around the entire input in Select ✅ 
- Focus is only on isClearable (no double focus) ✅
- Text overflow is properly cut off ⚠️ **This looks good, but would be even better if we could add like 8px of space between the ellipsis and the clear button so they never overlap at all**
![image](https://github.com/user-attachments/assets/c309840f-793c-43c1-b9f8-17cb21420eba)
- X is properly aligned for Select with left label ✅
- X is properly aligned for Select with top label ✅
- X is properly aligned for Multi Select with left label ⚠️ **How hard would it be to align to the center? It's center aligned for Combobox**
![image](https://github.com/user-attachments/assets/2f464559-2dfb-416c-8eda-af9b465f21a6)
- X is properly aligned for Multi Select with top label ⚠️ **It can get in this weird state where the X is over the text. Maybe if we add the space noted above, this could look even better**
![image](https://github.com/user-attachments/assets/77edd6b9-c5cc-4ae7-a9d4-d3dc72e8a08c) 
- isInverse uses correct colors for Select ✅
- Screenreader on Safari reads isClearable ✅
- Screenreader on Chrome reads isClearable ✅

**Combobox:**
- Focus around the entire input in Combobox ✅
- Focus is only on isClearable ✅
- Text overflow is properly cut off ✅
- X is properly aligned for Combobox with left label ✅
- X is properly aligned for Combobox with top label ✅
- X is properly aligned for Multi Combobox with left label ✅
- X is properly aligned for Multi Combobox with top label ✅
- isInverse uses correct colors for Combobox ✅
- Screenreader on Safari reads isClearable ✅
- Screenreader on Chrome reads isClearable ✅

2024-09-20 15:37 UTC, silvalaura commented on packages/react-magma-dom/src/components/Select/MultiSelect.tsx
> +  const clearIndicatori18n =
In this multiselect file, wouldn't we always want to use the multi label?

2024-09-24 14:08 UTC, silvalaura commented
We're almost there!

**Select:**
- Focus around the entire input in Select ✅ 
- Focus is only on isClearable (no double focus) ⚠️ **can it be moved _slightly_ more to the left to avoid the focus touching the arrow?**
![image](https://github.com/user-attachments/assets/ed1f71e5-9e0d-40c9-a53b-b43907dc3e78)
- Text overflow is properly cut off ✅
- X is properly aligned for Select with left label ✅
- X is properly aligned for Select with top label ✅
- X is properly aligned for Multi Select with left label ✅
- X is properly aligned for Multi Select with top label ✅
- isInverse uses correct colors for Select ✅
- Screenreader on Safari reads isClearable ✅
- Screenreader on Chrome reads isClearable ✅

**Combobox:**
- Focus around the entire input in Combobox ✅
- Focus is only on isClearable ✅
- Text overflow is properly cut off ✅  I noticed the issue below, but I can see it's an existing issue, so it does not need to be addressed at this time. 
![image](https://github.com/user-attachments/assets/ca7f31f1-24e2-4b62-908c-f2b50221c88c)
![image](https://github.com/user-attachments/assets/33c47990-0d2c-448a-b78b-b1c55d847e03)
- X is properly aligned for Combobox with left label ✅
- X is properly aligned for Combobox with top label ✅
- X is properly aligned for Multi Combobox with left label ✅
- X is properly aligned for Multi Combobox with top label ✅
- isInverse uses correct colors for Combobox ✅
- Screenreader on Safari reads isClearable ✅
- Screenreader on Chrome reads isClearable ✅

2024-09-24 17:35 UTC, orion-cengage approved these changes

2024-09-24 17:39 UTC, silvalaura approved these changes

2024-09-24 17:39 UTC, merged