Update Input additional children position based on lable position
cengage/react-magma pull request #1478
Opened 2024-10-07 14:51 UTC by moathabuhamad-cengage

Issue: #1163 

## What I did
Update Input additional children position based on lable position

## Screenshots:
![image](https://github.com/user-attachments/assets/81d5f3aa-cbeb-42b1-8fd0-51666bd06305)

## Checklist 
- [x] changeset has been added
- [x] Pull request description is descriptive
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## How to test
check Input with help link behavior based on label position and visibility

2024-10-08 17:41 UTC, silvalaura approved these changes
Looks good to me. Let's wait for @orion-cengage's approval before merging.

2024-10-09 12:47 UTC, orion-cengage requested changes
The button appears to be the correct size, but the icon inside is too large (24px). It needs to be smaller like it previously was (20px). I think it has taken on the size it was when it was previously INSIDE the input.

![image](https://github.com/user-attachments/assets/53ea5422-c048-460e-a0c5-8f61737c85f1)

2024-10-09 14:03 UTC, orion-cengage commented
Can we please expand the examples shown on the docs site to show the three variants: Top label, left label, no label.

Also, the Select component has the same ability to show a Help button, although I think it is technically done a little differently. We should at least update the title of that section of the page to also be "Help Link."

2024-10-09 14:15 UTC, moathabuhamad-cengage commented
> The button appears to be the correct size, but the icon inside is too large (24px). It needs to be smaller like it previously was (20px). I think it has taken on the size it was when it was previously INSIDE the input.
>


its currently set to behave like the IconButton which is the `theme.iconSizes.large` 32px on large inputs and `theme.iconSizes.medium` 24px on normal ones.  

![image](https://github.com/user-attachments/assets/c76eba91-33b7-43ca-882f-fc1200bd1986)

@orion-cengage  whats the correct behavior ? always 20px ?

2024-10-21 16:34 UTC, orion-cengage approved these changes

2024-10-21 17:40 UTC, silvalaura commented on packages/react-magma-dom/src/components/InputBase/index.tsx
> +function getHelpeLinkSVGSize(props) {
`getHelpLinkSVGSize` or `getHelperLinkSVGSize`

2024-10-21 17:40 UTC, silvalaura commented on .changeset/feat-input-help-text.md
> +feat(Input): Update Input additional children position based on lable position
```suggestion
feat(Input): Update Input additional children position based on label position
```

2024-10-22 07:47 UTC, merged