feat(treeview): add support for isDisabled
cengage/react-magma pull request #1480
Opened 2024-10-08 11:27 UTC by vitaliirumiantsev-cengage

Issue: #1305

## What I did

New feature: add support `isDisabled` prop for TreeView to disable all items
New feature: add support `isDisabled` field for items of `preselectedItems` prop to manage disabled state for items

## Checklist 
- [ ] changeset has been added
- [ ] Pull request description is descriptive
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test
Storybook > TreeView > Complex:
We can see that item 'Section 5.1.2' is disabled by setting `isDisabled` to true via  preselectedItems
We can switch TreeView's `isDisabled` prop to true to disable all items

2024-10-09 18:42 UTC, silvalaura requested changes
A few use cases that aren't working:
1. Simple: if I disable `itemId="0.0"`, the tree can't ever get focus
2. First Item branch: if I disable `itemId="Birds"`, the tree can't ever get focus
3. ~~Complex: if I press Clear All, and then try to "deselect" pt2ch5 by clicking the tag, it selects pt2ch5.2 and pt2ch5.3~~

We may want to put a disclaimer in the docs that the styling for isDisabled may not be visible if the user is passing a node to the label.

2024-10-10 11:56 UTC, vitaliirumiantsev-cengage commented on packages/react-magma-dom/src/components/TreeView/TreeItem.test.js
> +        <TreeView>
@silvalaura 
yes, we need this. because TreeItem depends on TreeViewContext that processed inside TreeView

2024-10-10 14:57 UTC, vitaliirumiantsev-cengage commented on packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
> +  isDisabled: false,
done

2024-10-10 14:57 UTC, vitaliirumiantsev-cengage commented on packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
> +    //
done

2024-10-10 14:58 UTC, vitaliirumiantsev-cengage commented on website/react-magma-docs/src/pages/api/tree-view.mdx
> +Pass the `isDisabled` prop to item inside `preselectedItems` prop to manage disabled state for the item
done

2024-10-10 14:58 UTC, vitaliirumiantsev-cengage commented on packages/react-magma-dom/src/components/TreeView/TreeView.test.js
> +      it('parent should have correct checkbox state and toggle children selection when some disabled children are partially selected', () => {
done

2024-10-10 14:58 UTC, vitaliirumiantsev-cengage commented on packages/react-magma-dom/src/components/TreeView/TreeView.test.js
> +              { itemId: 'item-child3', checkedStatus: IndeterminateCheckboxStatus.unchecked, isDisabled: true },
done

2024-10-10 16:25 UTC, silvalaura requested changes
Keyboard navigation looks good now. 

Last thing: currently if the whole tree isDisabled, `select all` and `clear all` still follow that behavior; nothing should happen in this case.

2024-10-11 07:24 UTC, vitaliirumiantsev-cengage commented on website/react-magma-docs/src/pages/api/tree-view.mdx
> +        <TreeItem label="Birds" itemId="selectable-birds">
done

2024-10-11 07:24 UTC, vitaliirumiantsev-cengage commented on website/react-magma-docs/src/pages/api/tree-view.mdx
> +  Toggle,
done

2024-10-11 07:24 UTC, vitaliirumiantsev-cengage commented on website/react-magma-docs/src/pages/api/tree-view.mdx
> +  Toggle,
done

2024-10-11 14:59 UTC, silvalaura approved these changes

2024-10-11 17:20 UTC, merged