Chore: Improve TypeScript, Linting, and Styling Support in Doc MDX Files
cengage/react-magma pull request #1588
Opened 2024-11-22 16:11 UTC by moathabuhamad-cengage

Issue: #1553 

## What I did
   - Updated ESLint configuration `.eslintrc.js` to include `@typescript-eslint/parser` and `mdx` plugins.
   - Added rules to handle MDX files and TypeScript.
   - Disabled specific rules for MDX files to avoid unnecessary warnings.
   - Added `lint`, `lint:fix`, and `lint:check` scripts for consistent linting.
   - Updated `format` script to include more file type

## Screenshots:
![Screenshot from 2024-11-22 15-03-38](https://github.com/user-attachments/assets/599e93fc-1d57-4167-af49-c4112b6a33ac)

## Checklist 
- [x] changeset has been added
- [x] Pull request description is descriptive
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes
- [-] I have added tests that prove my fix is effective or that my feature works

## How to test
- Run linting and formatting scripts
- Ensure MDX files are properly linted and formatted.
- Check for any linting or formatting errors.

2024-11-22 17:00 UTC, silvalaura reviewed
Haven't had a chance to navigate through every single page, but code wise this looks good!

2024-11-22 17:00 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/alert.mdx
> +        Im an Alert with <a href="#">linked text</a>
I'm

2024-11-25 08:30 UTC, moathabuhamad-cengage commented on website/react-magma-docs/src/pages/api/card.mdx
> +        alt="cat"
breaks eslint rule [jsx-a11y/img-redundant-alt](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/img-redundant-alt.md)

2024-11-25 08:58 UTC, moathabuhamad-cengage commented on website/react-magma-docs/src/pages/api/combobox.mdx
> -        updateSelectedItem(newChanges.selectedItem);
fixed

2024-11-26 14:39 UTC, silvalaura commented on website/react-magma-docs/src/pages/design/stepper.mdx
> +</figure>{' '}
![image](https://github.com/user-attachments/assets/82624240-05fb-43a1-b4b5-87353bfc7260)

2024-11-26 14:39 UTC, silvalaura commented on website/react-magma-docs/src/pages/design/stepper.mdx
> +</figure>{' '}
![image](https://github.com/user-attachments/assets/1e1c0296-e90b-4c25-8623-7d71d7e44094)

2024-11-26 14:58 UTC, silvalaura requested changes

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api-intro/styles-and-themes.mdx
![image](https://github.com/user-attachments/assets/d2bfbd07-a82e-4940-bf3d-588a29feb3d8)

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/appbar.mdx
Not part of this work necessarily, but I just noticed that `# AppBar Props` should be `## AppBar Props` so it appears on the secondary menu

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/buttongroup.mdx
Same with `# ButtonGroup Props` => `## ButtonGroup Props`

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/character-counter.mdx
`### Character Counter Props` => `## Character Counter Props`

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/dropzone.mdx
Can we change `## File Uploader Props` => `## Dropzone Props`

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/grid.mdx
`# Grid Props` => `## Grid Props`
&
`# Grid Items Props` => `## Grid Items Props`

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/icon.mdx
![image](https://github.com/user-attachments/assets/bd49035c-5646-40a9-ba3e-da69dc7276e5)

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/spacer.mdx
`# Spacer Props` => `## Spacer Props`

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/tooltip.mdx
![image](https://github.com/user-attachments/assets/46d05d50-31ac-4d78-bb55-8347e9aac7d3)

2024-11-26 14:58 UTC, silvalaura commented on website/react-magma-docs/src/pages/api/transition.mdx
`# Transition Props` => `## Transition Props`

2024-12-17 16:39 UTC, merged