Feature/datagrid
cengage/react-magma pull request #256
Opened 2021-05-05 19:09 UTC by rcgillet

2021-05-05 20:13 UTC, aaronmaturen requested changes

2021-05-05 20:13 UTC, aaronmaturen commented on packages/react-magma-dom/src/components/Datagrid/.prettierrc
> +  "tabWidth": 2,
Do you need this file?

2021-05-05 20:13 UTC, aaronmaturen commented on packages/react-magma-dom/src/components/Datagrid/Datagrid.stories.tsx
> +} from "../Pagination/usePagination";
This should probably just be exported from index.ts in Pagination?

2021-05-05 20:13 UTC, aaronmaturen commented on packages/react-magma-dom/src/components/Datagrid/useDatagrid.ts
> +/**
If there's no immediate plan for a hook here we can probably delete this

2021-05-05 20:13 UTC, aaronmaturen commented on packages/react-magma-dom/src/hooks/.prettierrc
> +{
Is this needed?

2021-05-05 20:13 UTC, aaronmaturen commented on packages/react-magma-dom/src/index.ts
> +export { usePagination } from './components/Pagination/usePagination';
We should just do `export * from ./components/pagination`

2021-05-06 17:40 UTC, joasmi723 commented on packages/react-magma-dom/src/components/Datagrid/index.ts
> +// export * from "./useDatagrid"
Can get rid of commented line, if we're not using this file.

2021-05-06 17:40 UTC, joasmi723 commented on website/react-magma-docs/src/pages/api/datagrid.mdx
> +**Any other props supplied will be provided to the wrapping `div` element.**
```suggestion
**Any other props supplied will be provided to the wrapping `table` element.**
```

2021-05-06 17:54 UTC, joasmi723 approved these changes

2021-05-06 17:54 UTC, rcgillet commented on packages/react-magma-dom/src/components/Datagrid/index.ts
> +// export * from "./useDatagrid"
```suggestion
```

2021-05-06 18:10 UTC, aaronmaturen approved these changes

2021-05-06 18:46 UTC, merged