feat(native select): adding the native select component
cengage/react-magma pull request #262
Opened 2021-05-11 18:08 UTC by ccedrone

2021-05-12 13:41 UTC, joasmi723 requested changes

2021-05-12 13:41 UTC, joasmi723 commented on packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
> +  hasError?: boolean;
You shouldn't have to specify a lot of these props here (helperMessage, isInverse, etc) -- they should already be included when you extend the `InputProps`.   

We also shouldn't need a consumer to provide a `hadError` prop.  We should be able to determine this if by whether the `errorMessage` prop is empty.

2021-05-12 13:41 UTC, joasmi723 commented on packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
> +        <SelectTriggerButton toggleButtonProps={''} disabled={disabled}>
The inverse version isn't getting the correct focus style, and the red border isn't showing up for the error message.  I think you might need to add `isInverse={isInverse}` and `hasError={!!errorMessage}` (or something similar) here.

2021-05-12 13:41 UTC, joasmi723 commented on packages/react-magma-dom/src/components/NativeSelect/useNativeSelect.ts
> +/**
If you're not using this file, you can just delete it.

2021-05-12 13:41 UTC, joasmi723 commented on packages/react-magma-dom/src/index.ts
> +export { NativeSelect } from './components/NativeSelect';
```suggestion
export { NativeSelect, NativeSelectProps } from './components/NativeSelect';
```

2021-05-12 13:41 UTC, joasmi723 commented on website/react-magma-docs/src/pages/api/native-select.mdx
> +      hasError
The consumer shouldn't need to specify `hasError` because they're including an `errorMessage` prop.

2021-05-12 13:41 UTC, joasmi723 commented on website/react-magma-docs/src/pages/api/native-select.mdx
> +## Inverse with error
```suggestion
## Inverse with Error
```

2021-05-12 13:41 UTC, joasmi723 commented on website/react-magma-docs/src/pages/api/native-select.mdx
> +## Inverse disabled
```suggestion
## Inverse Disabled
```

2021-05-12 13:41 UTC, joasmi723 commented on packages/react-magma-dom/src/components/NativeSelect/NativeSelect.stories.tsx
> +  hasError: true,
User shouldn't need to specify `hasError` if they are also providing an errorMessage.

2021-05-12 13:57 UTC, joasmi723 commented on website/react-magma-docs/src/pages/api/native-select.mdx
> +
We might also want to show an example with an onChange event, to demonstrate getting the select's value.

2021-05-17 14:48 UTC, joasmi723 commented on website/react-magma-docs/src/pages/api/native-select.mdx
> +**Any other props supplied will be provided to the wrapping `div` element.**
```suggestion
**Any other props supplied will be provided to the wrapping `select` element.**
```

2021-05-17 15:12 UTC, joasmi723 approved these changes

2021-05-18 20:13 UTC, orion-cengage approved these changes
Looks good.

2021-05-19 16:05 UTC, merged