feat(input): added isClearable prop to input base
cengage/react-magma pull request #280
Opened 2021-05-26 19:08 UTC by jamiesmyln

re #266

2021-05-27 13:32 UTC, orion-cengage requested changes
We need to make sure the clear button styling is consistent across all the inputs.  The Combobox currently used the round button:
![image](https://user-images.githubusercontent.com/24397282/119834774-dec1a700-bec5-11eb-8e5e-5f6acfa90a5a.png)

While the Search input is using the square button:
![image](https://user-images.githubusercontent.com/24397282/119834852-eed98680-bec5-11eb-8a68-4ba2eda5f535.png)

Since the Date Picker and Search inputs already use square buttons for their main action, let's just use square buttons for the Clear button as well.  This means updating Combobox.

2021-06-01 14:09 UTC, joasmi723 requested changes

2021-06-01 14:09 UTC, joasmi723 commented on packages/react-magma-dom/src/components/InputBase/index.tsx
> +          <IsClearableContainer theme={theme}>
When I tab through the Search field, I notice the Search button gets focused before the X button, which doesn't match what I'm seeing visually.  Can we switch the order of these elements in the dom so it matches the visual?

2021-06-01 14:09 UTC, joasmi723 commented on packages/react-magma-dom/src/components/InputBase/index.tsx
> +              aria-label={'Clear Input'}
We should move this message into the i18n config.

2021-06-08 14:37 UTC, joasmi723 commented on packages/react-magma-dom/src/components/InputBase/index.tsx
> +          <IsClearableContainer theme={theme}>
Awesome, this looks great!  

One other thing I hadn't noticed before is that after the clicking the 'clear' icon, nothing is in focus. I think we should return the focus to the search box.  

This PR also needs a changeset.  Everything else looks good to me.

2021-06-08 19:36 UTC, merged