feat(tag): adding initial branch for design review
cengage/react-magma pull request #289
Opened 2021-06-09 16:31 UTC by ccedrone

2021-06-15 18:23 UTC, orion-cengage requested changes
Please make the following changes:

1. I'm not seeing a section on the API docs page for the small sizes

2. Change the labels on the examples to just: Default, Primary, Low Contrast, High Contrast
![image](https://user-images.githubusercontent.com/24397282/122101910-79811780-cdda-11eb-889d-cd03c54829a5.png)

3. Change labels on examples to just: Disabled, Disabled Low Contrast
![image](https://user-images.githubusercontent.com/24397282/122101992-90c00500-cdda-11eb-9c52-ff51eaa731e9.png)

4. Change labels on examples to just: Inverse Default, Inverse Primary, Inverse Low Contrast, Inverse High Contrast
![image](https://user-images.githubusercontent.com/24397282/122102114-b3eab480-cdda-11eb-9c13-bf7ec853ce65.png)

5. Change labels on examples to just: Inverse Disabled, Inverse Disabled Low Contrast
![image](https://user-images.githubusercontent.com/24397282/122102288-e4cae980-cdda-11eb-969d-e83531feb5b3.png)

6. I think the titles of these sections should be "Tag With Icon" and "Deletable Tag With Icon"
![image](https://user-images.githubusercontent.com/24397282/122102949-a124af80-cddb-11eb-8bbc-201aff750cce.png)
![image](https://user-images.githubusercontent.com/24397282/122102992-aeda3500-cddb-11eb-9526-d83e9e5397e3.png)

7. Small tag with delete button: The right margin on the close button icon should be 4px, not 2px
![image](https://user-images.githubusercontent.com/24397282/122103573-653e1a00-cddc-11eb-82ff-7bfc6bd4882e.png)

2021-06-15 18:30 UTC, orion-cengage commented
@ccedrone I forgot one update to make.  The API Docs page needs the button in the upper-right that goes to the Design Guidelines page.

2021-06-23 14:09 UTC, rcgillet requested changes

2021-06-23 14:09 UTC, rcgillet commented on packages/react-magma-dom/src/i18n/default.ts
> +    deleteAriaLabel: 'Delete tag',
This should be more descriptive. We do something in `Combobox` to use the `labelText`.

`'reset selection for {labelText}. {selectedItem} is selected',`. So here we could do `delete {labelText} tag`. Then in the `Tag`  component file you can do something like this ```const deleteAriaLabel = i18n.tag.deleteAriaLabel.replace(/\{labelText\}/g, labelText)```

2021-06-23 14:09 UTC, rcgillet commented on website/react-magma-docs/src/pages/api/tag.mdx
> +<DeleteableTagProps />
Above each of the `props` tables put `### Deletable Tag Props` or `### Clickable Tag Props` so they know what they are looking at.

2021-06-23 14:52 UTC, orion-cengage approved these changes
Styling is looking good.

2021-06-28 18:06 UTC, rcgillet approved these changes

2021-06-28 18:16 UTC, merged

2021-06-28 18:18 UTC, ccedrone commented
In the development of this component, pimaryInverse was needed. This ticket was resolved as part of the work: https://github.com/cengage/react-magma/issues/260