fix(modal): fix medium modal width, add widths to theme
cengage/react-magma pull request #30
Opened 2020-12-15 20:51 UTC by joasmi723

2020-12-16 16:02 UTC, orion-cengage approved these changes
Verified updates to modals look good.

2020-12-16 16:05 UTC, rcgillet requested changes

2020-12-16 16:05 UTC, rcgillet commented on package-lock.json
> +      "resolved": "http://nexus.mindtap.corp.web/content/groups/npm.group/confusing-browser-globals/-/confusing-browser-globals-1.0.10.tgz",
Switched back to nexus

2020-12-17 14:02 UTC, rcgillet approved these changes

2020-12-17 15:26 UTC, merged