Feature/file upload
cengage/react-magma pull request #319
Opened 2021-07-13 16:57 UTC by aaronmaturen

2021-10-05 20:57 UTC, orion-cengage approved these changes
The file uploader is looking good to me and ready to be reviewed by Perkins after we publish it.

2021-10-18 14:55 UTC, rcgillet requested changes

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/FileIcon.tsx
> +export interface FileIconProps extends IconProps {
Do these props need the typedoc information?

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +export interface PreviewProps extends Omit<FlexProps, 'behavior'> {
typedoc

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +    const handleRemoveFile = (file: FilePreview) => {
small thing, but in all of our other components we use the `function {x}` format

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +      if (onRemoveFile && typeof onRemoveFile === 'function') {
in all of our other components we use `{x} && typeof {x} === 'function' && {x}({y})`

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +      const [done, setDone] = useState(false);
```suggestion
      const [done, setDone] = useState<boolean>(false);
```

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +              aria-label="Remove File"
hardcoded. needs i18n

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +              onClick={() => {
`file` is in `props`. No need for the `() => remove(file)`

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +              style={{ marginTop: '4px' }}
hardcoded

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +              onClick={() => {
no need for `() => delete(file)`

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +              aria-label="Delete File"
hardcoded. i18n

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/Preview.tsx
> +                <Thumb role="img" id="THISISTHETHUMBNAIL" file={file} />
why the id?

2021-10-18 14:55 UTC, rcgillet commented on packages/file-uploader/src/components/fileuploader/utils.ts
> +  if(bytes == 0) return '0 Bytes';
not 100%, but does `Bytes` need to be added to the i18n stuff?

2021-10-18 15:51 UTC, aaronmaturen commented on packages/file-uploader/src/components/fileuploader/FilePreview.ts
> +export interface FileError {
just internal again

2021-11-01 12:59 UTC, orion-cengage requested changes
Perkins Testing:
1. The text "Upload files" is implemented as a label element for an input that is hidden via display:none. When this text is clicked it opens the file browser, which is unexpected because the text does not look like an actionable control. Consider removing the label element from this text and use a span instead.
2. The div that contains the drop zone for the file uploader has a tabindex="0" attribute making it focusable with the keyboard. When this region gains focus it does not show a visible focus indicator. This could be confusing for keyboard users. Since there is a "Browse Files" button that gains keyboard focus and opens the file chooser, the <div> does not also need to gain focus. Therefore consider removing the tabindex attribute.
![image](https://user-images.githubusercontent.com/24397282/139675691-b0f3c28b-81d8-47e2-a503-a748b4564bda.png)

3. After uploading a file, screen readers can access content with role="progressbar" that is not visible. This progressbar has a value of "zero percent" which makes it seem as though the file has yet to be uploaded. If this element is not meant to be visible it should not be detected by screen readers. Otherwise if it is meant to communicate the progress of the uploaded file it should show some visual indication in the UI as well as in the code.
![image](https://user-images.githubusercontent.com/24397282/139675781-10beee41-4278-4372-ba5e-241a53c82f6f.png)

2021-11-02 17:06 UTC, aaronmaturen commented
fixed the issues from perkins

2021-11-02 17:09 UTC, orion-cengage approved these changes

2021-11-08 15:37 UTC, merged