fix(modal): add useFocusLock hook. fix weird focus states
cengage/react-magma pull request #326
Opened 2021-07-20 17:07 UTC by rcgillet

2021-07-20 18:38 UTC, aaronmaturen requested changes

2021-07-20 18:38 UTC, aaronmaturen commented on packages/react-magma-dom/src/components/Modal/Modal.tsx
> +// import {
delete the comments 😈

2021-07-20 18:38 UTC, aaronmaturen commented on packages/react-magma-dom/src/hooks/useFocusLock.ts
> +import * as React from 'react';
should we create a docs page for this? Makes sense that other teams (or components external to dom) would want this too

2021-07-20 18:38 UTC, aaronmaturen commented on packages/react-magma-dom/src/hooks/useFocusLock.ts
> +import * as React from 'react';
in the same vein... we should export it in `./src/index.ts`

2021-07-20 18:38 UTC, aaronmaturen commented on packages/react-magma-dom/src/components/Modal/Modal.tsx
> +// import {
probably delete that code from utils also...

2021-07-20 18:38 UTC, aaronmaturen commented on packages/react-magma-dom/package.json
> +    "@testing-library/user-event": "^13.2.0",
testing-library is at the root level... and if they're here, versions must match

2021-07-20 18:38 UTC, aaronmaturen commented on packages/react-magma-dom/package.json
> +    "@testing-library/user-event": "^13.2.0",
this is why package-lock showed up

2021-07-21 13:55 UTC, jamiesmyln approved these changes
I didn't notice any strange behavior with components that use modals.

2021-07-23 16:06 UTC, aaronmaturen approved these changes

2021-07-26 13:19 UTC, merged