feat: initial commit of the block quote component
cengage/react-magma pull request #426
Opened 2021-12-21 17:27 UTC by ccedrone

2021-12-22 13:51 UTC, orion-cengage requested changes
1. Can we add a space in between the m-dash and the attribution?
![image](https://user-images.githubusercontent.com/24397282/147102637-23d5daaf-9e33-42e4-ae58-5da822b985de.png)

2.  Since the quotation marks are built into the component, can we make sure we're using smart quotes, so they look less like this:
![image](https://user-images.githubusercontent.com/24397282/147102896-957f91f5-92a0-4236-994d-b2f1b884107c.png)

and more like this? 
![image](https://user-images.githubusercontent.com/24397282/147102945-5c86b60b-ad3a-4ab6-9a49-e82f51758dc9.png)

I think it's a matter of using these:
![image](https://user-images.githubusercontent.com/24397282/147103098-9a7bda4f-aa44-498d-87fc-9d5caf98df84.png)

2021-12-27 16:59 UTC, aaronmaturen requested changes
https://css-tricks.com/quoting-in-html-quotations-citations-and-blockquotes/#hey-what-about-the-figure-element

we should probably use `figure` `blockquote` and `figcaption` for these...

2022-01-24 16:09 UTC, orion-cengage approved these changes

2022-01-24 16:27 UTC, rcgillet requested changes

2022-01-24 16:27 UTC, rcgillet commented on packages/react-magma-dom/src/components/BlockQuote/BlockQuote.test.js
> +  it('should render the visually hidden component', () => {
test description doesn't make sense.

2022-01-24 16:27 UTC, rcgillet commented on packages/react-magma-dom/src/components/BlockQuote/BlockQuote.tsx
> +            magma.colors[borderStyle] ? magma.colors[borderStyle] : borderStyle
```suggestion
            magma.colors[borderStyle] || borderStyle
```

2022-01-24 16:27 UTC, rcgillet commented on packages/react-magma-dom/src/components/BlockQuote/BlockQuoteItem.tsx
> +          : color || TypographyColor.default
```suggestion
        color || hasAttribution ? TypographyColor.subdued : TypographyColor.default
```

2022-01-24 16:27 UTC, rcgillet commented on packages/react-magma-dom/src/components/BlockQuote/BlockQuoteItem.tsx
> +          : visualStyle || TypographyVisualStyle.bodyLarge
```suggestion
      visualStyle={
        visualStyle || hasAttribution ? TypographyVisualStyle.bodyMedium : TypographyVisualStyle.bodyLarge
```

2022-01-24 17:41 UTC, rcgillet approved these changes

2022-01-31 21:41 UTC, merged