feat(inputs): updating Inputs with rebrand styles
cengage/react-magma pull request #659
Opened 2022-04-26 20:35 UTC by silvalaura

re https://github.com/cengage/react-magma/issues/444 & https://github.com/cengage/react-magma/issues/445

2022-04-28 14:10 UTC, orion-cengage requested changes
Feedback:

- Please change the border on the container's error state to 1px instead of 2px
![image](https://user-images.githubusercontent.com/24397282/165767688-b476597c-6fbd-42bc-a929-d2bf6bc6d2a0.png)

- The placeholder text on inverse inputs looks too light.  Please make sure it's neutral100 at 70% opacity.
Actual:
![image](https://user-images.githubusercontent.com/24397282/165768747-ade4cb30-c256-4183-ac93-6f9c1b1c5293.png)

Expected: 
![image](https://user-images.githubusercontent.com/24397282/165768837-9833c6b1-05b2-45f3-a2f1-fdc46220b290.png)

- Please update the weight of the field label to 500 (Medium).  This was not in the original AC.
![image](https://user-images.githubusercontent.com/24397282/165769471-80fbc56d-99f2-4852-a904-17b5e2e99e5e.png)

2022-04-28 17:00 UTC, silvalaura commented
@orion-cengage ready for re-review!

2022-05-02 13:38 UTC, greenervigil approved these changes

2022-05-02 18:15 UTC, ccedrone approved these changes

2022-05-04 16:10 UTC, orion-cengage approved these changes

2022-05-04 17:49 UTC, merged