feat(datepicker): update DatePicker with new colors
cengage/react-magma pull request #719
Opened 2022-05-19 16:58 UTC by silvalaura

2022-05-20 03:03 UTC, greenervigil requested changes
The keyboard shortcuts are not using the correct inverse text.  This should be addressed here as well.  

<img width="324" alt="Captura de Pantalla 2022-05-19 a la(s) 22 59 19" src="https://user-images.githubusercontent.com/16470877/169441798-47fd1b19-d705-4873-abe4-8038b41552a2.png">

2022-05-24 18:25 UTC, orion-cengage requested changes
The border on the dropdown container looks too bright.  It should be using the same border styling as the dropdown component.

![image](https://user-images.githubusercontent.com/24397282/170106023-cd74b610-e36c-4216-93e9-8fd13c8dcfea.png)

2022-05-25 15:31 UTC, orion-cengage requested changes
Looks like this bug got introduced in 2.5.7.  The dropdown on the date picker is incorrectly overlapping the input instead of appearing 2px below it.

![image](https://user-images.githubusercontent.com/24397282/170300072-c54873bd-40d2-4064-accd-9cb3d4de6a80.png)

2022-05-26 18:17 UTC, greenervigil approved these changes

2022-05-26 18:43 UTC, merged