docs(breakpointscontainer): update breakpoints container examples
cengage/react-magma pull request #730
Opened 2022-05-24 18:44 UTC by silvalaura

fix #701

2022-05-24 20:26 UTC, orion-cengage requested changes
Looks like the text is changing to neutral-700 instead of **primary**-700.  Please do primary-700 because it's still not passing accessibility.

2022-05-25 14:17 UTC, silvalaura commented
> Looks like the text is changing to neutral-700 instead of **primary**-700. Please do primary-700 because it's still not passing accessibility.

I have replaced tertiary700 with warning500 as the background color, so it can pass accessibility with white text (using Card inverse) instead of customizing font color just for these examples.

2022-05-25 15:04 UTC, orion-cengage approved these changes

2022-05-25 19:06 UTC, ccedrone approved these changes

2022-05-25 20:33 UTC, merged