feat(datagrid): Add `isSortableBySelected` prop to DataGrid
cengage/react-magma pull request #856
Opened 2022-07-28 20:35 UTC by silvalaura

This fix was released as part of 2.6.0 (https://github.com/cengage/react-magma/pull/841) so just copying those changes to v3.

2022-08-01 12:45 UTC, orion-cengage requested changes
1. I think we should make the other two columns in the example sortable as well so there's an example of how different sortable columns work together.
2. The focus style on the arrow needs to be solid instead of dashed
![image](https://user-images.githubusercontent.com/24397282/182149992-ea1865a6-ac06-425d-bc08-e592c6306dcb.png)
![image](https://user-images.githubusercontent.com/24397282/182150035-1d952b60-0dd1-47be-937f-81ed59a994f9.png)

3. When the column is not currently sorted and has the double arrow, it's supposed to be a lighter gray (neutral-500) than when it is sorted (neutral-700).  _See regular table component for example._
![image](https://user-images.githubusercontent.com/24397282/182150208-d79ae173-29dd-435a-9139-c60dae36801e.png)
![image](https://user-images.githubusercontent.com/24397282/182150257-dbd650bc-67b8-48b1-9c95-f651055a4f41.png)

![image](https://user-images.githubusercontent.com/24397282/182150883-e5ca08c4-df91-4509-aee8-7b2e315ae599.png)

2022-08-02 12:46 UTC, orion-cengage approved these changes

2022-08-02 14:00 UTC, ccedrone approved these changes

2022-08-03 13:07 UTC, greenervigil approved these changes

2022-08-03 14:28 UTC, merged