fix(input): inputs with long placeholders && `isClearable` have appropriate padding
cengage/react-magma pull request #962
Opened 2022-11-03 19:25 UTC by silvalaura

Issue: #955

## What I did

For inputs that are clearable, we know pass the input length to the input so that it only has the space for the clearable x after the input has some characters.

## Screenshots (if appropriate):

## Checklist 
- [ ] changeset has been added
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test

2022-11-04 13:20 UTC, ccedrone approved these changes

2022-11-09 20:29 UTC, orion-cengage requested changes
Your fix doesn't seem to be working properly on Search input

![image](https://user-images.githubusercontent.com/24397282/200935297-ede4f95b-df8a-42a4-97b4-7cada8184df1.png)

2022-11-10 14:08 UTC, silvalaura commented
> Your fix doesn't seem to be working properly on Search input. I couldn't change the placeholder, but entered text is overlapping the clear button.
> 
> ![image](https://user-images.githubusercontent.com/24397282/200935297-ede4f95b-df8a-42a4-97b4-7cada8184df1.png)

That was weird. There must have been a problem with the build because it wasn't showing the control to change the placeholder field, but it did appear when I pulled the branch. Anyway, I merged with master to force a rebuild and it seems to be working again.

2022-11-14 17:15 UTC, greenervigil approved these changes

2022-11-14 20:12 UTC, orion-cengage approved these changes

2022-11-14 20:49 UTC, merged